### ISSUE TITLE
Coreograph: dearrayed TIFFs not showing up in Pathviewer

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#100]
Ajit points out that after he uploaded the dearrayed cores to OMERO, they're displaying in the traditional viewer. We want Pathviewer!
Need to check what are the requirements for it to show up in Pathviewer.

**Comment by clarenceyapp** [comment]
@ArtemSokolov can you update the setup.nf file to pull
af56eaba4df0163fa1c17ece8198a043d7d1929c

This will fix it. Tested successfully on exemplar-002.

**Comment by ArtemSokolov** [comment]
I advanced the O2 install in `/n/groups/lsp/mcmicro/2020-04-10/Coreograph/` to `af56eaba4df0163fa1c17ece8198a043d7d1929c` as a temporary fix, so @ajitjohnson can use it right away.

I'll add the formal change to `setup.nf` in the next version bump (since we're likely to incorporate the fix to the x-y mix up at some point also).
