### ISSUE TITLE
user version control/version tracking of individual modules?

### ISSUE THREAD

**Issue by hungyiwu** [labsyspharm/mcmicro#143]
Is it possible to select/pin which version of individual modules (docker images) to use? Also, for the outputs, is there a file where individual module version numbers are recorded?

**Comment by ArtemSokolov** [comment]
The current version of each module can be seen in the config: https://github.com/labsyspharm/mcmicro-nf/blob/dadf43ed46a2ed7a51c7eb2559b4744178d8cbe7/nextflow.config#L5-L11

It also gets written by the pipeline to `qc/provenance/params.yml` in each run.

You can overwrite these on the command line with, e.g., `--unmicst-version 1.2.1`. **NOTE that putting this inside the YAML file you provide with -params-file will have no effect**, because config has higher precedence than `-params-file`, but lower precedence than the command line. However, you can overwrite the default config values with your own personal config file, which you provide to nextflow with `-c`: https://www.nextflow.io/docs/latest/config.html#configuration-file
