### ISSUE TITLE
We need a small (tiny) exemplar

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#15]
The exemplar is too large and too slow to process. We need something that can be executed under 1min.

**Comment by ArtemSokolov** [comment]
It might be hard to get under 1min. Exemplar-001 is made of 2x3 tiles and takes a little under 5min to run through every single module (including ASHLAR) on my desktop. Pre-stitched, it's a little over 2min.

Should we consider having fewer cycles?

**Comment by DenisSch** [comment]
How many cycles do we have now?

**Comment by ArtemSokolov** [comment]
Both exemplars have 10 cycles.

**Comment by DenisSch** [comment]
Do we have to modify the .rcpnl file to remove the cycles? If this can be done without "disturbing" the original file structure I would suggest to go down to 3 cycles.
Every second longer will accumulate with each test we are running - especially if we want to implement a UnitTest

**Comment by ArtemSokolov** [comment]
Do we need to go all the way up to .rcpnl? Can we not just exclude

`exemplar-001/raw_images/exemplar-001-cycle-04.ome.tiff`

through

`exemplar-001/raw_images/exemplar-001-cycle-10.ome.tiff`

while keeping

`exemplar-001/raw_images/exemplar-001-cycle-0[1-3].ome.tiff` ?

I can just have `exemplar.nf` pull down cycles 1-3 from S3 instead of 1-10. Or am I misunderstanding something?

**Comment by ArtemSokolov** [comment]
If we can simply exclude the `.ome.tiff` files, the change is as simple as putting `1..3` instead of `1..10` here:

https://github.com/ArtemSokolov/mcmicro-nf/blob/4eb04be81d5d7fff60431c0035313ae2a5ed2277/exemplar.nf#L23

**Comment by DenisSch** [comment]
Sounds good! Let's do it that way!
