### ISSUE TITLE
Add documentation that explains how to interpret quantification output

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#224]
New users are loading the wrong label mask and comparing it to the wrong csv file. Just for clarify, it would help to have the name of the masks either in the filename or a header of the csv file.

**Comment by ArtemSokolov** [comment]
@clarenceyapp The mask names are already in the header. Each column name contains a suffix that specifies which mask its quantifies. For example, here's one containing both `_cellMask` and `_nucleiMask` suffixes:

```
CellID,DNA_1_cellMask,AF488_cellMask,AF555_cellMask,AF647_cellMask,DNA_2_cellMask,A488_background_cellMask,A555_background_cellMask,A647_background_cellMask,DNA_3_cellMask,FDX1_cellMask,CD357_cellMask,CD1D_cellMask,X_centroid,Y_centroid,column_centroid,row_centroid,Area,MajorAxisLength,MinorAxisLength,Eccentricity,Solidity,Extent,Orientation,DNA_1_nucleiMask,AF488_nucleiMask,AF555_nucleiMask,AF647_nucleiMask,DNA_2_nucleiMask,A488_background_nucleiMask,A555_background_nucleiMask,A647_background_nucleiMask,DNA_3_nucleiMask,FDX1_nucleiMask,CD357_nucleiMask,CD1D_nucleiMask
```

We can't really put these suffixes in the filename, since there is no upper limit on the number of masks that a quantification file may contain.

My guess is that the user may be working with a tool that implicitly trims those suffixes. Otherwise, I don't see how it would be possible to load the wrong mask when you are looking at a column named `CD1D_nucleiMask`.

**Comment by clarenceyapp** [comment]
@ArtemSokolov i think users are not aware that nucleiMask literally refers to the file with the name nucleiMask, or the connection isn't immediately obvious. Perhaps more documentation is needed in interpreting the output csv file. There is adequate documentation for how to run mcmicro but I'm not aware of anything beyond that.

**Comment by ArtemSokolov** [comment]
Yea, that sounds reasonable.
