### ISSUE TITLE
Error executing process > 'registration:ashlar'

### ISSUE THREAD

**Issue by jiangfuqing** [labsyspharm/mcmicro#257]
Hi,
When I run the example command belows, it reports an error. Could you help me to figure out the reason?
Best.

(python37) [fqjiang_gdl@c26 ~]$ nextflow run labsyspharm/mcmicro --in mcmicro/exemplar-001
N E X T F L O W  ~  version 20.10.0
Launching `labsyspharm/mcmicro` [nauseous_khorana] - revision: e93c60f78e [master]
executor >  local (1)
[-        ] process > illumination        -
[40/4d15ce] process > registration:ashlar [  0%] 0 of 1
[-        ] process > dearray:coreograph  -
[-        ] process > probmaps:unmicst    -
executor >  local (1)
[-        ] process > illumination        -
[40/4d15ce] process > registration:ashlar [100%] 1 of 1, failed: 1 ✘
[-        ] process > dearray:coreograph  -
[-        ] process > probmaps:unmicst    -
[-        ] process > probmaps:cypository -
[-        ] process > probmaps:ilastik    -
[-        ] process > segmentation:s3seg  -
[-        ] process > quantification      -
[-        ] process > naivestates         -
Error executing process > 'registration:ashlar'

Caused by:
  Process `registration:ashlar` terminated with an error exit status (127)

Command executed:

  ashlar 'exemplar-001-cycle-01.ome.tiff' 'exemplar-001-cycle-02.ome.tiff' 'exemplar-001-cycle-03.ome.tiff' -m 30 --ffp exemplar-001-cycle-01-ffp.tif exemplar-001-cycle-02-ffp.tif exemplar-001-cycle-03-ffp.tif --dfp exemplar-001-cycle-01-dfp.tif exemplar-001-cycle-02-dfp.tif exemplar-001-cycle-03-dfp.tif --pyramid -f exemplar-001.ome.tif

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 63: docker: command not found

Work dir:
  /public/home/fqjiang_gdl/work/40/4d15ce81093e1969d5270eea0c02b3

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by DenisSch** [comment]
@jiangfuqing It looks like Docker is either not running or not installed.

Ensure that the Docker engine is running by typing `docker images`
Install Docker: https://docs.docker.com/get-docker/

**Comment by DenisSch** [comment]
@jiangfuqing I would like to follow up - is it working now?

**Comment by jiangfuqing** [comment]
> @jiangfuqing I would like to follow up - is it working now?
Dear DenisSch,
I‘m sorry for reply so latter, but I havn't the root permission to install Docker in the super computer server and the administrator says he wouldn't install the Docker. So I have no idea about this. Any suggestions would be helpful, thanks!
Best!
Fuqing.

**Comment by ArtemSokolov** [comment]
Hi, @jiangfuqing 

Does your server admin allow Singularity (https://sylabs.io/singularity/), which is an alternative to Docker that lets you run containers without root permissions?

If so, we can help you get the pipeline running with Singularity.

**Comment by jiangfuqing** [comment]
> Hi, @jiangfuqing
> 
> Does your server admin allow Singularity (https://sylabs.io/singularity/), which is an alternative to Docker that lets you run containers without root permissions?
> 
> If so, we can help you get the pipeline running with Singularity.

**Comment by jiangfuqing** [comment]
Hi, DenisSch
Yeah, The Singularity is allowed to install. Very thanks for help to build the pipeline running with Singularity.
Best!
Fuqing

**Comment by ArtemSokolov** [comment]
Hi @jiangfuqing,

I just added a configuration profile for singularity. After you install Singularity, fetch the latest version of the pipeline with `nextflow pull` and use the new config profile with `-profile`:
```
nextflow pull labsyspharm/mcmicro
nextflow run labsyspharm/mcmicro --in /path/to/exemplar-001 -profile singularity
```

**Comment by Nyasud** [comment]
When I ran exemplar-001 with Singularity as below, I got the following error:
Could you help me how to solve it?
Regards,

$ nextflow run \
>     labsyspharm/mcmicro \
>     --in /home/u0xx/test/exemplar-001 \
>     -profile singularity 
N E X T F L O W  ~  version 22.10.0
Launching `https://github.com/labsyspharm/mcmicro` [mighty_lamarr] DSL2 - revision: 82d92e793c [master]
executor >  local (1)
[-        ] process > illumination                -
[5e/f5280e] process > registration:ashlar         [  0%] 0 of 1
[-        ] process > dearray:coreograph          -
[-        ] process > segmentation:roadie:runTask -
[-        ] process > segmentation:worker         -
[-        ] process > segmentation:s3seg          -
[-        ] process > quantification:mcquant      -
[-        ] process > downstream:worker           -
[-        ] process > viz:roadie:runTask          -
[-        ] process > viz:autominerva             -
Error executing process > 'registration:ashlar'

Caused by:
  Process `registration:ashlar` terminated with an error exit status (1)

Command executed:

executor >  local (1)
[-        ] process > illumination                -
[5e/f5280e] process > registration:ashlar         [100%] 1 of 1, failed: 1 ✘
[-        ] process > dearray:coreograph          -
[-        ] process > segmentation:roadie:runTask -
[-        ] process > segmentation:worker         -
[-        ] process > segmentation:s3seg          -
[-        ] process > quantification:mcquant      -
[-        ] process > downstream:worker           -
[-        ] process > viz:roadie:runTask          -
[-        ] process > viz:autominerva             -
Error executing process > 'registration:ashlar'

Caused by:
  Process `registration:ashlar` terminated with an error exit status (1)

Command executed:

  ashlar 'exemplar-001-cycle-06.ome.tiff' 'exemplar-001-cycle-07.ome.tiff' 'exemplar-001-cycle-08.ome.tiff'  -m 30 --ffp exemplar-001-cycle-06-ffp.tif exemplar-001-cycle-07-ffp.tif exemplar-001-cycle-08-ffp.tif --dfp exemplar-001-cycle-06-dfp.tif exemplar-001-cycle-07-dfp.tif exemplar-001-cycle-08-dfp.tif -o exemplar-001.ome.tif

Command exit status:
  1

Command output:
  Stitching and registering input images
  Cycle 0:
      reading exemplar-001-cycle-06.ome.tiff

Command error:
  Stitching and registering input images
  Cycle 0:
      reading exemplar-001-cycle-06.ome.tiff
  Traceback (most recent call last):
    File "/usr/local/bin/ashlar", line 8, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 212, in main
      return process_single(
    File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 237, in process_single
      reader = build_reader(filepaths[0], plate_well=plate_well)
    File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 358, in build_reader
      reader = reader_class(path, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 398, in __init__
      self.metadata = BioformatsMetadata(self.path)
    File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 210, in __init__
      self._init_metadata()
    File "/usr/local/lib/python3.10/dist-packages/ashlar/reg.py", line 234, in _init_metadata
      self._reader.setId(self.path)
    File "jnius/jnius_export_class.pxi", line 1177, in jnius.JavaMultipleMethod.__call__
    File "jnius/jnius_export_class.pxi", line 885, in jnius.JavaMethod.__call__
    File "jnius/jnius_export_class.pxi", line 982, in jnius.JavaMethod.call_method
    File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
  jnius.JavaException: JVM exception occurred: exemplar-001-cycle-06.ome.tiff (No such file or directory) java.io.FileNotFoundException

Work dir:
  /home/u0xx/work/5e/f5280e8577352eda73bf4d7104d641

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
