### ISSUE TITLE
Unmicst failing GPU call on O2 cluster

### ISSUE THREAD

**Issue by mpagarjohnson** [labsyspharm/mcmicro#347]
I am trying to run the pipeline on a non-GPU node on the O2 cluster per the instructions provided on the website. The pipeline is failing on Unmicst with a failed call to cuInit. I am attaching the script used to submit the job to O2 and the error log I received.
[submit_mcmicro_1.log](https://github.com/labsyspharm/mcmicro/files/7915400/submit_mcmicro_1.log)
[run.log](https://github.com/labsyspharm/mcmicro/files/7915402/run.log)

**Comment by ArtemSokolov** [comment]
@mpagarjohnson Are you able to process `exemplar-001` on O2 with
```
nextflow run labsyspharm/mcmicro --in /path/to/exemplar-001 -profile O2ext
```
or are you getting the same CUDA errors?

@clarenceyapp Is there anything particular in the `mousenucleiDAPI` model that may be forcing UnMicst to always use GPUs?

**Comment by mpagarjohnson** [comment]
exemplar-001 runs with no issues.

**Comment by ArtemSokolov** [comment]
Thanks for checking, @mpagarjohnson. Looks like we'll need to examine `mousenucleiDAPI` to see why it's forcing GPU usage. In the meantime, consider submitting to GPU nodes on O2. I just tweaked config profiles. Pull the new version with

```
nextflow pull labsyspharm/mcmicro
```

and you should be able to just replace `-profile O2ext` with `-profile O2ext,O2gpu` (note no space after the comma) to get UnMicst jobs submitted to the GPU nodes on O2.

**Comment by mpagarjohnson** [comment]
Great, thank you! For the shell script to submit the job, should I also change '#SBATCH -p short' to '#SBATCH -p gpu'?

**Comment by ArtemSokolov** [comment]
That's not needed. The shell script submits the top-level `nextflow` job, which doesn't take advantage of GPUs, so there is no additional advantage to having it in the `gpu` queue.

**Comment by clarenceyapp** [comment]
Hi @mpagarjohnson ,
The docs needs some updating but you would need to add `--tool unmicst-legacy` to your list of `unmicst-opts` since the mouse model only works with the old version, which is no longer default. Everything else in the options list appears fine.

**Comment by FloWuenne** [comment]
I had a similar issue today with unmicst failing on one of our cluster nodes.

Our cluster has a CentOS system running with slurm. Ashlar ran fine on a normal node, but unmicst failed 

```
System: Linux 3.10.0-1160.53.1.el7.x86_64
 Runtime: Groovy 3.0.9 on OpenJDK 64-Bit Server VM 11.0.14+9-LTS
 Encoding: UTF-8 (UTF-8)
 CPUs: 2 - Mem: 19.6 GB (8.7 GB) - Swap: 0 (0)
```

Command:

```
nextflow  -c nextflow_config_mcmicro.GPU.txt run labsyspharm/mcmicro -profile singularity --in exemplar-001
```

I had to change the `process.queue = 'gpu-legacy'` for unmicst to finish without a problem. 

This was the error message when running unmicst in singularity on the cluster on a node without gpu.

```
ERROR nextflow.processor.TaskProcessor - Error executing process > 'segmentation:worker (unmicst-1)'

Caused by:
  Missing output file(s) `*.tif` expected by process `segmentation:worker (unmicst-1)` (note: input files are not included in the default matching set)

Command executed:

  python /app/unmicstWrapper.py --stackOutput --outputPath .  exemplar-001.ome.tif

Command exit status:
  0

Command output:

  WARNING! USING unmicst-solo AS DEFAULT. THIS MODEL HAS BEEN TRAINED ON MORE TISSUE TYPES. IF YOU WANT THE LEGACY MODEL, USE --tool unmicst-legacy

  python /app/UnMicst1-5.py  exemplar-001.ome.tif --channel 0 --outputPath . --mean -1 --std -1 --scalingFactor 1 --GPU -1 --outlier -1 --stackOutput

Command error:
  Illegal instruction
```

Is there a way to set parameters so unmicst runs on non-GPU nodes?

**Comment by ArtemSokolov** [comment]
@FloWuenne UnMicst should be runnable in a CPU-only environment. The GitHub Action that tests Singularity functionality seems to work without problems: https://github.com/labsyspharm/mcmicro/runs/4915107583?check_suite_focus=true#step:6:58

I could be wrong, but my understanding is that GitHub virtual machines do not expose GPUs. (At least, their [docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) don't mention a GPU, but I never actually tested it.) UnMicst also works on CPU-only nodes on our SLURM cluster running Singularity. So, this is quite puzzling to me.

Can you share what you have in `nextflow_config_mcmicro.GPU.txt`? One thought is that maybe your Singularity options include `--nv`, which exposes a GPU to be visible inside the container and could be causing issues on a CPU-only node on your cluster.

Can you try running the singularity container by hand and tell me if you get the following output?

```
(base) sokolov@giskard:~/test/exemplar-001$ ls
exemplar-001.ome.tif

(base) sokolov@giskard:~/test/exemplar-001$ singularity shell -B "$PWD" -C docker://labsyspharm/unmicst:2.7.0

Singularity> cd ~/test/exemplar-001
Singularity> python /app/unmicstWrapper.py --stackOutput --outputPath .  exemplar-001.ome.tif

WARNING! USING unmicst-solo AS DEFAULT. THIS MODEL HAS BEEN TRAINED ON MORE TISSUE TYPES. IF YOU WANT THE LEGACY MODEL, USE --tool unmicst-legacy

python /app/UnMicst1-5.py  exemplar-001.ome.tif --channel 0 --outputPath . --mean -1 --std -1 --scalingFactor 1 --GPU -1 --outlier -1 --stackOutput
sh: 1: nvidia-smi: not found
Using CPU
loading data
loading data
loading data
0.34
0.25
2022-02-03 17:23:04.483745: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (-1)
Model restored.
Using channel 1
Inference...
Inference...
Inference...

Singularity> ls
exemplar-001.ome.tif  exemplar-001_Probabilities_1.tif  qc
```

Some explanation:
* `-C` isolates the container from the host machine to prevent any issues with overlapping libraries, etc.
* `-B "$PWD"` exposes the present working directory, which contains exemplar-001.ome.tif (output from ASHLAR), to the container
* Without `--nv`, the GPU is not exposed to the container. This is characterized by `nvidia-smi` not being a valid command (the command would display GPU information when the container is initialized with `--nv`) and cuInit failing. Tensorflow then falls back on using CPU only.

**Comment by FloWuenne** [comment]
Thanks for looking into this @ArtemSokolov ! 

My nextflow config so far only contained a general process definition and some java parameter:

```
env.JAVA_TOOL_OPTIONS = "-Xmx100m"

process{
  executor = 'slurm'
  queue = 'single'
  cpus     = 1
  time     = '20m'
  memory   = '6GB'
}
```

I ran the unmicst command directly on the .ome.tiff file from the registration step in the singularity container that I entered as you suggested. I get the same error as before on our login node. 

```
singularity shell -B "$PWD" -C ./singularity_cache/labsyspharm-unmicst-2.7.0.img

Singularity> python /app/unmicstWrapper.py --stackOutput --outputPath .  exemplar-001.ome.tif

WARNING! USING unmicst-solo AS DEFAULT. THIS MODEL HAS BEEN TRAINED ON MORE TISSUE TYPES. IF YOU WANT THE LEGACY MODEL, USE --tool unmicst-legacy

python /app/UnMicst1-5.py  exemplar-001.ome.tif --channel 0 --outputPath . --mean -1 --std -1 --scalingFactor 1 --GPU -1 --outlier -1 --stackOutput
Illegal instruction
```

**Comment by ArtemSokolov** [comment]
Thanks for the quick feedback, @FloWuenne. It's good that the issue is reproducible! I guess the question is how to debug it, since I don't how I can reproduce your issue on my side.

It looks like it has no problems running the wrapper, which then passes control to `UnMicst1-5.py`. It also looks like the latter is failing early, since we don't see any output. Can you try a few more things to help narrow down what the issue may be?

**1) Test that Tensorflow works**

```
$ singularity exec -C docker://tensorflow/tensorflow:2.1.0-py3 python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
```

**2) Test that the Tensorflow GPU container falls back on CPU when the GPU is not exposed via `--nv`**

```
$ singularity exec -C docker://tensorflow/tensorflow:2.1.0-gpu-py3 python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
```

**3) Test that exporting an environmental variable works in Python**

```
$ singularity exec -C docker://labsyspharm/unmicst:2.7.0 python -c "import os; os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'"
```

**4) Test that Tensorflow v1 is supported**
```
$ singularity exec -C docker://labsyspharm/unmicst:2.7.0 python -c "import tensorflow.compat.v1 as tf; tf.disable_v2_behavior()"
```

My thinking is that we are not seeing `sh: 1: nvidia-smi: not found`, which means that execution never reaches the [corresponding system calls](https://github.com/HMS-IDAC/UnMicst/blob/78cfdc1b3b131044c5ab590857a7c18f099b6c0c/UnMicst1-5.py#L739). However, we know that `os.system()` works, since that's what `unmicstWrapper.py` uses to call `UnMicst1-5.py`. So, the failure must occur somewhere in the [header](https://github.com/HMS-IDAC/UnMicst/blob/78cfdc1b3b131044c5ab590857a7c18f099b6c0c/UnMicst1-5.py#L1-L26).

My suspicion is that the issue may be with the code still using Tensorflow v1 (Test 4). We have been talking about upgrading to use a more recent version of TF anyway, so this may be a good incentive.

**Comment by mpagarjohnson** [comment]
@FloWuenne Just in case this helps, as Clarence said above in this thread there are some options for unmicst that are incompatible with the current build and require the flag --tool unmicst-legacy, the error that I received above was because of this compatibility issue and when I ran the job again with unmicst-legacy enabled I was able to use the CPU-only nodes. Maybe try that if you haven't already?

**Comment by FloWuenne** [comment]
@ArtemSokolov Thanks again for your quick answer and suggestions!

I tried all of your suggestions, here are the results on the login node of our cluster:

**1) Test that Tensorflow works** ✅ 
**2) Test that the Tensorflow GPU container falls back on CPU when the GPU is not exposed via --nv** ✅ 
**3) Test that exporting an environmental variable works in Python** ✅ 
**4) Test that Tensorflow v1 is supported** ✅ 

For all the test commands you send, singularity ran them but didn't give me any output, so I am guessing this means there was no error thrown either? Seems like they all ran without issues, meaning none of these should be the problem? I have only tested this on the login node though, since I thought that since it doesn't have a gpu, would probably mimic a non gpu node.

@mpagarjohnson I tried running the same command using `--tool unmicst-legacy` inside the `unmicst-opts` now on a cpu only node. For exemplar-001 it seems to work. Using the same approach on actual data however brings back the `  Illegal instruction` error I mentioned earlier!

**Comment by ArtemSokolov** [comment]
@FloWuenne Thanks for running the tests. This is quite puzzling, especially since it seems that whether `--tool unmicst-legacy` works depends on the input dataset.

I am talking to @DenisSch about possibly getting a guest account on your cluster. I think the easiest path forward may be for me to jump on and play around with the UnMicst container to see if I can nail down what's happening.

My only other thought right now is that the following function may be causing issues: https://github.com/HMS-IDAC/UnMicst/blob/master/toolbox/GPUselect.py

Can you please do one more quick test?
```
singularity exec -C docker://labsyspharm/unmicst:2.7.0 nvidia-smi
```
The expected output is "command not found":
```
/.singularity.d/actions/exec: 21: exec: nvidia-smi: not found
```
However, if we see "Illegal instruction", then we will just rework how GPU selection is handled, such that it doesn't rely on `nvidia-smi`.

**Comment by clarenceyapp** [comment]
Hi @FloWuenne 
Since you asked the difference between Unmicst 1 and 1.5, Unmicst v1.5 was trained on substantially more training data and augmentations on 6 different human tissue types. It is likely going to give better results than Unmicst v1, which was only trained on tonsil and lung.

Clarence

**Comment by FloWuenne** [comment]
Thanks for the clarification on unmicst @clarenceyapp ! 

@ArtemSokolov The pipeline did run on the CPU-only node today using the actual standard unmicst (v1.5) today. It might have been that the error was mainly related to available memory on the nodes that I was submitting too for the actual data that I was trying to analyze. 

I did try the tests you asked for and this was the result:

```
singularity exec -C docker://labsyspharm/unmicst:2.7.0 nvidia-smi
INFO:    Using cached SIF image
FATAL:   "nvidia-smi": executable file not found in $PATH 
```

Since I was able to run MCMICRO using unmicst on the actual data I needed to analyze. I guess my issue is resolved, although I am not 100% sure why (best guess is memory issue). 

Thanks for all your help everyone!

**Comment by jmuhlich** [comment]
If you wouldn't mind, could you re-run the command you ran in the Singularity shell to reproduce the problem, but with the Python `faulthandler` module enabled? This will let us get a traceback even though some low-level code is terminating abruptly:

 `PYTHONFAULTHANDLER=1 python /app/unmicstWrapper.py --stackOutput --outputPath .  exemplar-001.ome.tif`

Thanks.

**Comment by FloWuenne** [comment]
Sorry that it took some time to rerun this command @jmuhlich!

Here is the output from the command with `faulthandler` enabled:

```
Singularity> PYTHONFAULTHANDLER=1 python /app/unmicstWrapper.py --stackOutput --outputPath . exemplar-001.ome.tif

WARNING! USING unmicst-solo AS DEFAULT. THIS MODEL HAS BEEN TRAINED ON MORE TISSUE TYPES. IF YOU WANT THE LEGACY MODEL, USE --tool unmicst-legacy

python /app/UnMicst1-5.py  exemplar-001.ome.tif --channel 0 --outputPath . --mean -1 --std -1 --scalingFactor 1 --GPU -1 --outlier -1 --stackOutput
Fatal Python error: Illegal instruction

Current thread 0x00002b3ac9d52f40 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 922 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 658 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 684 in _load
  File "/usr/lib/python3.6/imp.py", line 343 in load_dynamic
  File "/usr/lib/python3.6/imp.py", line 243 in load_module
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24 in swig_import_helper
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/__init__.py", line 49 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 994 in _gcd_import
  File "/usr/lib/python3.6/importlib/__init__.py", line 126 in import_module
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 44 in _load
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 50 in __getattr__
  File "<frozen importlib._bootstrap>", line 947 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/__init__.py", line 40 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 101 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 941 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 941 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "/app/UnMicst1-5.py", line 8 in <module>
Illegal instruction
```

**Comment by ArtemSokolov** [comment]
Thanks for providing these logs, @FloWuenne.

It seems that the code crashes on `import tensorflow.compat.v1 as tf`, which is strange, since test number 4 above passed successfully. The only thing I can think of is that there may be a conflict in the libraries being imported.

Either way, I propose that we close the issue for now, since you have a working version. However, if you keep running into this issue, I will look into getting an account on your cluster, so I can debug the problem directly.
