### ISSUE TITLE
quantification error 1, IndexError

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/mcmicro#364]
Dear MCMICRO developers,

Thank you for developing such a versatile tool.

I am running it on a simple 2 marker imaging setup, nuclei and cytoplasm markers. Unmicst quality control looks good, Seg qc also looks good. For some reason upon hitting mcquant it runs into an error (see attached txt file).
[20220228_MCMICRO_19_bug.txt](https://github.com/labsyspharm/mcmicro/files/8154566/20220228_MCMICRO_19_bug.txt)

Is there something I am missing? Image file and marker file download link: 
https://filetransfer.mdc-berlin.de/?u=QEVNRpnW&p=fbAnDUJv 

Thank you again,
Best,
Jose

**Comment by ArtemSokolov** [comment]
Hi @josenimo,

Your `markers.csv` appears to be delimited by semicolons, instead of commas. The quantification module is then parsing the file as a single-column `.csv` and assumes that you are simply providing marker names in the legacy "one name per line" format. So, it determines that you have three markers, the first one being `channel_number;cycle_number;marker_name;filter`, the second one `1;1;Hoechst;Hoechst` and the third one `2;1;NaK_Pump;488`.

If you replace semicolons with commas, quantification should be able to parse the file correctly and identify the `marker_name` column. However, let us know if you are still running into issues.

Best,
-Artem

EDIT: I also noticed that you are using a fairly old version of the pipeline. A more recent version should provide a more informative message when there is a mismatch between the number of markers in `markers.csv` and the input image. You should be able to pull the most recent version with:
```
nextflow pull labsyspharm/mcmicro
```

**Comment by josenimo** [comment]
Thank you @ArtemSokolov, it was silly of me to not double check the separation.

**Comment by josenimo** [comment]
Dear @ArtemSokolov,

I reopened this issue because I am running into another problem with mcquant, I have not been using mcmicro in a while so maybe I am missing something or doing something silly again. I am uploading the whole folder with the files in there, I hope the netflow log is enough as a trace. 

Thank you again for your help!
Best, Jose

link: https://filetransfer.mdc-berlin.de/?u=V8FR88JH&p=CRnRF8Vj

**Comment by josenimo** [comment]
never mind I figured it our, the stacking from ImageJ looked correct but it was in 4D, all good
