### ISSUE TITLE
Can't use params.yml file with nextflow

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/mcmicro#390]
Dear mcmicro developer,

I tried using a parameters file to simplify copy pasting into cmd, but for some reason it runs into an error. I ran normal mcmicro, copied the params file from qc, and try rerunning with that but it still runs into error. I tried deleting few things from params file but to no avail.

(MCMICRO) josenimo@CMP04801:~/MCMICRO/MCMICRO_28$ nextflow run labsyspharm/mcmicro -params-file params.yml
N E X T F L O W  ~  version 21.10.6
Launching labsyspharm/mcmicro [cheeky_bhaskara] - revision: 4e06319f2d [master]
--quantification-mask is deprecated; please use --quant-opts '--masks ...'

 -- Check script '/home/josenimo/.nextflow/assets/labsyspharm/mcmicro/main.nf' at line: 45 or see '.nextflow.log' file for more details

link for download: https://filetransfer.mdc-berlin.de/?u=ZZwB9fDQ&p=Zn7rWYG3

Thank you in advance!
Best,
Jose

**Comment by ArtemSokolov** [comment]
Hi @josenimo,

Good to hear from you again. I hope you're doing well.

The problem is completely my fault. I need to clean up what MCMICRO writes to `params.yml`, so that the file can be reused with `-params-file`. Please delete the following lines in `params.yml`:

* `module*` (i.e., `moduleIllum`, `moduleRegistr`, etc.)
* `maskSpatial`, `maskAdd`, `quantificationMask`, and `nstatesOpts`
* `contPfx`

After removing these lines, the pipeline passes through probability map calculation and segmentation. It errors out on quantification with `Exception: mcquant supports only 2D/3D images.`, but sounds like you already figure it out based on https://github.com/labsyspharm/mcmicro/issues/364

**Comment by ArtemSokolov** [comment]
TODO:

- [x] Clean up how the pipeline checks for legacy parameters. Currently, it initializes them to empty strings and then checks whether the user overwrote that. This leads to the legacy parameters being written out to `qc/params.yml`, which triggers the deprecation warnings in subsequent runs when `qc/params.yml` is passed via `-params-file`. Instead, the deprecation checks should verify the existence of these parameters via `params.containsKey()`.
- [x] Move module specifications and container prefix (currently, `params.module*` and `params.contPfx`) out of the parameter namespace. These are specified via configuration files and can/should be controlled via the `-c custom.config` mechanism, instead.
