### ISSUE TITLE
Is it possible to perform tissue classification with mcmicro?

### ISSUE THREAD

**Issue by kaizen89** [labsyspharm/mcmicro#439]
Hi,
I would like to perform tissue classification such as stroma vs tumor and get the information of cells assigned to either stroma or tumor. Is that currently possible with `mcmirco` ?
Thanks

**Comment by clarenceyapp** [comment]
Hi @kaizen89, MCMICRO will not do that directly. The core functions in MCMICRO will only quantify the marker intensity of each cell and present it in the form of a table. It would be then up to you to classify each cell into stromal and tumor based on knowledge of what markers should be expressed in stromal vs tumor. Once you've separated cells into these two groups (as well as any other groups), then you can begin to look for spatial patterns since you have each cell's morphology measurements and X,Y coordinates. Please let us know if you have further questions.

Clarence

**Comment by kaizen89** [comment]
Hi @clarenceyapp,It is actually not that simple, first a given cell type can be present both in stroma and in tumor tissue, second, even if your cells are not present in both tissues, you would still loose information of cell density as you do not have the area of stroma vs tumor. Thus, you would loose a lot of spatial and important information I believe many users are interested in. Maybe exporting the cell mask to a software where you could do tissue classification could work.

**Comment by clarenceyapp** [comment]
@kaizen89 Ok, I think I know what you actually want now, which was different from my initial understanding. You want to identify the areas of tumor and stromal first and then analyze the cell composition and their spatial characteristics within those regions. MCMICRO does not do that either. Currently, in our publications, we have relied on pathologists to annotate tumor and stromal areas based on H&E and/or specific immunofluorescence markers to get the general area. We then refer back to the MCMICRO csv files to pull out cells contained within those areas for further analysis. We have tried to use pathologist annotations to train models to automatically identify these regions but it is still a work in progress. As you say, maybe there are commercial or open source software that already can do that. HALO AI and QuPath look like they have some pre-trained or trainable tissue segmentation models.
