### ISSUE TITLE
How to execute background substraction?

### ISSUE THREAD

**Issue by ciszew** [labsyspharm/mcmicro#466]
Hello
I noticed that the background subtraction option became avaiable in mcmicro. Would it be possible to get step-by-step instructions how to structure input directories and files to include background subtraction in mcmicro run?

**Comment by ArtemSokolov** [comment]
@kbestak @FloWuenne Do you have an example dataset that you used to prototype your background subtraction module?

**Comment by kbestak** [comment]
Hi, 
This is the current way to perform background subtraction in MCMICRO:
1. .ome.tif image with autofluorescence channels in the registration folder
2. markers.csv with:
    a) "background" column with values TRUE for autofluorescence channels
    b) "exposure" column with the exposure times used for channel acquisition. This is crucial for scaling if there are different exposure times between the channel and autofluorescence.
    c) "Filter" column specifying in which channel the image is acquired. This is crucial for matching the autofluorescence channel to a stain.
4. when specifying your run, add the tag --background, or have the params.yml contain:
```
workflow:
  background: true
```
5. The output image is a pyramidal ome tiff with a pixel-by-pixel and it will be in the background folder, the autofluorescence channels will be subtracted from channels with the same "Filter" value pixel-by-pixel, and they would be excluded from the final image. The markers_bs.csv will also be saved in the background folder to match the output image.
6. If a run has the --background tag, then any module which needs an image, or marker file will look for a precomputed intermediate in the background folder and use that image and marker file for their respective use.

@ArtemSokolov How should I share an example image?

Another thing to add, once I have time, I will be changing the script to be able to subtract any channel from any other channel, and not only the autofluorescence from all channels with that filter. The markers.csv will then just require the "background" column which would specify which channel should be subtracted, and all channels will be kept in that output image. This use case should be in function by New Year's and all documentation will be updated accordingly.

**Comment by ciszew** [comment]
Thank you!, this works well. Only comment i have is that if background images are not at the end of the stack the markers_bs.csv file doesnt update the channel numbering correctly after background images are removed from the original ome.tiff file.  Easy fix is to have background at the end of the stack or if not then resume pipeline after changing markers_bs.csv manually

**Comment by janinemelsen** [comment]
Just as a double check, is this what you mean?:

![image](https://user-images.githubusercontent.com/50010499/221304051-0649d3ca-98e4-4473-a4ba-882a82de6644.png)

I still receive the error  'dataframe object has no attribute 'background'

**Comment by kbestak** [comment]
Hi, apologies for the lack of updates in this thread. I've updated the documentation here: https://mcmicro.org/parameters/other.html#backsub

As mentioned in my previous comment, I've updated how the background channels get specified so that any channel can be subtracted from any channel. Here is an example of a markers.csv file: https://github.com/SchapiroLabor/Background_subtraction/blob/main/example/markers.csv
![image](https://user-images.githubusercontent.com/86408271/221374409-397b753e-a450-4019-a977-68b53a74284a.png)

From module version v0.3.0 onward, the "background" column specifies which channel should be subtracted from the channel in the "marker_name" column. The values in the "background" column, if specified, must match a value in the "marker_name" column. The "filter" column can be excluded for this module. The "exposure" column remains unchanged and I've added the option to specify which channels should be excluded from the output image to save space (such as the autofluorescence channels, extra DAPI channels) with the "remove" column as shown in the example.

**Comment by janinemelsen** [comment]
Perfect, it works! Thank you!

**Comment by FloWuenne** [comment]
Awesome, thanks @kbestak ! @ciszew  can we close this issue now?☺️

**Comment by ciszew** [comment]
Yes! definitively 👍. Option to remove any channel in new version of backsub is fantastic, allows me to reduce size and preclean mosaic file before next step of analysis. Thank you again.
