### ISSUE TITLE
failed to pull singularity image

### ISSUE THREAD

**Issue by janinemelsen** [labsyspharm/mcmicro#478]
I am using nextflow on a slurm cluster and try to run the example dataset, but encounter the following error (even after I try to adjust the directory of the .singularity folder:

<img width="1448" alt="Screenshot 2023-02-13 at 21 06 16" src="https://user-images.githubusercontent.com/50010499/218620678-49606b08-0b36-4805-a5f7-94489154b3f8.png">

How can I fix this?

Thanks!

Janine

**Comment by ArtemSokolov** [comment]
Hi Janine,

What happens if you pull the image manually, outside of MCMICRO?

```
singularity pull --name labsyspharm-ashlar-1.17.0.img docker://labsyspharm/ashlar:1.17.0
```

**Comment by janinemelsen** [comment]
Outside of mcmicro it does work:
<img width="1192" alt="Screenshot 2023-02-13 at 22 03 24" src="https://user-images.githubusercontent.com/50010499/218628432-246d59b1-0fa6-424c-9ade-d0bee5d24cf5.png">

Janine

**Comment by ArtemSokolov** [comment]
Hmm, could be a random hiccup with Nextflow and/or Singularity. (I've seen `pull` commands timeout due to network problems before.) I would try again. Alternatively, you can manually move the `.img` file you downloaded to the `NXF_SINGULARITY_CACHEDIR` directory. Nextflow will then treat it as cache and not attempt to download it again.

**Comment by janinemelsen** [comment]
Today, no error at least until the segmentation task;) 

<img width="1174" alt="Screenshot 2023-02-14 at 20 43 59" src="https://user-images.githubusercontent.com/50010499/218914139-b0cadf57-73e7-4c5a-aa2d-b50cdb1d873c.png">

**Comment by ArtemSokolov** [comment]
This is a bit strange. Exit code 255 can sometimes be associated with networking issues (depending on the application).

Since you are able to download containers by hand, a possible workaround is to pre-download them all using manual `singularity pull` commands and put the resulting `.img` files into your cache directory. You can find container names and versions for all modules starting on line 19 of https://github.com/labsyspharm/mcmicro/blob/master/config/defaults.yml#L19

I am curious if this issue is MCMICRO-specific. When you have time, can you try any of the `nf core` pipelines (https://nf-co.re/pipelines) with `-profile singularity` to see if Nextflow and/or Singularity fails to download containers for those pipelines as well? If you encounter similar issues, it may require a conversation with your cluster administrator to get to the root of the problem. Nextflow is quickly becoming the dominant tool for running complex pipelines, so I'm sure the admins would be very interested in having an environment where it works without issues.

**Comment by janinemelsen** [comment]
Hmm maybe it is a memory issue after all.. I changed 

`export NXF_SINGULARITY_CACHEDIR=/exports/klim-hpc/Janine/.singularity`
 into
`export SINGULARITY_CACHEDIR=/exports/klim-hpc/Janine/.singularity`

and now everything is working.

**Comment by ArtemSokolov** [comment]
Great to hear you got it working!
