### ISSUE TITLE
Speed up run?

### ISSUE THREAD

**Issue by wesleylcai** [labsyspharm/mcmicro#550]
I searched through issues but could not find a good answer - what is the best way to utilize my institution's HPC resources to run MCMICRO faster?

I am using singularity, and my institution's HPC cluster which has access to many GPUs and node configurations. Does MCMICRO benefit from more GPUs, more nodes? What is the optimal configuration of my nextflow.config file to speed up my runs?

Thanks in advance.

**Comment by josenimo** [comment]
what steps are the bottleneck for you? 
How large are your files?
How long does it take? 
What kind of HPC executor is it? (SLURM, SGE, AWS?)

**Comment by ArtemSokolov** [comment]
Hi @wesleylcai,

There are some examples of configs in [config/nf/](https://github.com/labsyspharm/mcmicro/tree/master/config/nf) that may helpful. In particular,

* `wsi.config` shows how to specify the number of CPUs, memory and runtime for individual processes
* `O2base.config` shows how to use a SLURM-based HPC with Singularity containers
* [This example](https://github.com/labsyspharm/mcmicro/blob/master/nextflow.config#L58-L68) shows how to request GPUs from HPC nodes.

If your HPC uses SLURM, there is a good chance you should be able to just do:
```
nextflow run labsyspharm/mcmicro /path/to/exemplar-001 -profile O2ext,WSI,GPU
```
where the [O2ext profile](https://github.com/labsyspharm/mcmicro/blob/master/nextflow.config#L31-L34) will store downloaded containers inside `.mcmicro/` directory in your home folder.

You can override any of these properties by creating a `custom.config`, specifying the desired settings in it, then feeding to MCMICRO with `-c`:

```
nextflow run labsyspharm/mcmicro /path/to/exemplar-001 -profile O2ext,WSI,GPU -c custom.config
```
which will use values from `custom.config` and fall back to defaults in the specified profiles otherwise.

**Comment by wesleylcai** [comment]
Thanks both for the suggestions.
- I am using SLURM
- I ran Examplar-002 which took 18 minutes and the bottleneck looks like Registration, with unmicst following second (see below)

<img width="200" alt="Examplar-002_times" src="https://github.com/labsyspharm/mcmicro/assets/29263514/ead5ec3e-081a-41b4-9a57-18ca1d3c8531">




- I ended up trying different CPU/mem combinations on Examplar-001 and it looks like 10 cpu and 240GB is the sweet spot

<img width="500" alt="Examplar-001" src="https://github.com/labsyspharm/mcmicro/assets/29263514/6f810a80-c8e8-4edd-bf90-fb31b693108d">


Do you think there is room for increasing performance? Just wanted to ask before running a large batch of samples.

**Comment by ArtemSokolov** [comment]
I think that you will probably get the best speed up from running each sample on a separate HPC node. Having a few CPUs allocated to each run is a good idea, as is having enough memory for the size of your images.

**Comment by josenimo** [comment]
@wesleylcai I think those numbers are completely fine, imo further optimisations would have to be done at the module level.
I think you can also try to go lower with memory, sure it helps to have more, but in my experience you would then lose more time waiting in the queue for those high RAM jobs, than actually running modules. Like artem mentioned, enough ram to load the image into memory, for exemplar001, technically 5gb is sufficient.

**Comment by wesleylcai** [comment]
Thank you both!
