### ISSUE TITLE
Clarification on Cell-Type Assignment Process in NaiveStates: Role of Gaussian Mixture Models and Naive Bayes?

### ISSUE THREAD

**Issue by ke2rchan** [labsyspharm/mcmicro#555]
Hello! Posting this issue to get a better understand behind how naivestates works!

I am not very knowledgable in the mathematical calculations used, but I am currently using naivestates for my automated cell type assignment. However, I was not able to find any detailed explanation on the naivestates github on how exactly this cell type assignment is done. Is it done using both Gaussian Mixture Models and Naive Bayes? It seems like it is not the cell type with the highest probability that gets assigned as seen below. ('Myeloid cell''s value has the highest value but the cell type assigned for cell ID-14 is still assigned as 'others'.) Would greatly appreciate any explanations as to how exactly the cell type assignment is done! :)

<img width="481" alt="image" src="https://github.com/labsyspharm/mcmicro/assets/173441509/661aea7d-fca1-4495-bf84-faf9572dda0c">

**Comment by ke2rchan** [comment]
also, for the UMAP generated by NaiveStates, what data or inputs are used to compute it?

**Comment by ArtemSokolov** [comment]
Hi @ke2rchan,

Yes, the method uses Gaussian Mixture Models to assign a probability that a marker is expressed in a given cell, then combines those probabilities using Naive Bayes based on the user-provided marker -> cell-type dictionary to derive the overall probability of each cell type. Take a look at the [older version of README](https://github.com/labsyspharm/naivestates/blob/c2883858ade6676fe7c289c2804044279ca7db8c/README.md) (before the tool was containerized) for some additional information.

There is a [threshold](https://github.com/labsyspharm/naivestates/blob/master/R/clsf.R#L41) that the probability must exceed for a cell type to be selected. In your example, there is only a 9% chance associated with Myeloid cells and 0% with everything else. That means that there is a 100 - 9 = 91% chance that the cell is something else, which is why the final label is "Other".

The UMAP produced by the tool is constructed using the probabilities derived from Gaussian Mixture Models as inputs.

**Comment by ke2rchan** [comment]
@ArtemSokolov I see! Thank you so much for your help and patience with me with all these questions! :)
