### ISSUE TITLE
Change the profile for downstream analysis (e.g. scimap, flowsom...)

### ISSUE THREAD

**Issue by emir-radkevich** [labsyspharm/mcmicro#567]
Hi.

I have a question.

I am using mcmicro on HPC machine and using this command to run analysis on my lab's images from segmentation to downstream:
```
ml nextflow/24.04.4.5917; nextflow run /sc/arion/projects/HIMC/software/mcmicro_orion --in /sc/arion/scratch/radkee01/mcmicro_test2 --start-at segmentation --stop-at downstream --downstream scimap,flowsom,naivestates -profile singularity,GPU
```

I noticed, that all downstream options have been running on GPU, which is not what I intended. As far as I understand, I do not need to use GPU for these steps. [segmentation is running on GPU, quantification -- on default computational nodes]

How can I change this behavior to use default settings from ```nextflow.config```?

Thank you,
Emir.

**Comment by ArtemSokolov** [comment]
Hi @emir-radkevich,

We have a highly-customizable `worker` process that allows us to add new modules to the pipeline without writing additional Nextflow code (by simply modifying `config/defaults.yml`). Both `segmentation` and `downstream` steps use it, which is why the `GPU` profile is affecting both.

I just pushed a fix that does a better job resolving the two. Can you do `nextflow pull labsyspharm/mcmicro` and try launching your job again? All `downstream` processes should now be sent the CPU queue on your HPC.

**Comment by emir-radkevich** [comment]
> Hi @emir-radkevich,
> 
> We have a highly-customizable `worker` process that allows us to add new modules to the pipeline without writing additional Nextflow code (by simply modifying `config/defaults.yml`). Both `segmentation` and `downstream` steps use it, which is why the `GPU` profile is affecting both.
> 
> I just pushed a fix that does a better job resolving the two. Can you do `nextflow pull labsyspharm/mcmicro` and try launching your job again? All `downstream` processes should now be sent the CPU queue on your HPC.

Thank you.
Works perfectly.
